const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let currentCategory=null,currentPayment=null,currentLevel=null,currentRate=null,currentDiscount=0,couponUsed=false;
const fmt=n=>`Rs ${Number(n).toLocaleString('en-IN')}`;
const nameInput=$('#nameInput'),navName=$('#navName'),loginChip=$('#loginChip'),loginState=$('#loginState'),categoryStep=$('#categoryStep'),productStep=$('#productStep'),productTitle=$('#productTitle'),productHint=$('#productHint'),productGrid=$('#productGrid'),selectionText=$('#selectionText'),selectionMeta=$('#selectionMeta'),modal=$('#productModal'),modalBody=$('#modalBody'),modalTitle=$('#modalTitle'),modalDesc=$('#modalDesc'),modalCategory=$('#modalCategory'),toast=$('#toast');
$('#year').textContent=new Date().getFullYear();
function toastMsg(message){toast.textContent=message;toast.classList.add('show');toast.style.display='block';clearTimeout(window._toast);window._toast=setTimeout(()=>{toast.classList.remove('show');toast.style.display='none'},2500)}
function setLoggedIn(name){localStorage.setItem('ff_sell_name',name);navName.textContent=name;loginChip.textContent='LOGGED IN';nameInput.value=name;nameInput.readOnly=true;$('#saveName').textContent='Saved ✓';loginState.textContent='✓ Name saved on this browser/device.';$('.profile-action').style.display='inline-block';categoryStep.classList.remove('locked')}
const saved=localStorage.getItem('ff_sell_name');if(saved)setLoggedIn(saved);
$('#saveName').onclick=()=>{const n=nameInput.value.trim();if(!n)return toastMsg('Enter your name first.');setLoggedIn(n);toastMsg(`Welcome, ${n}.`);categoryStep.scrollIntoView({behavior:'smooth',block:'center'})};
nameInput.addEventListener('keydown',e=>{if(e.key==='Enter')$('#saveName').click()});
$('#profileAction').onclick=()=>{localStorage.removeItem('ff_sell_name');location.reload()};
$('#heroStart').onclick=()=>$('#shop').scrollIntoView({behavior:'smooth'});$('#scrollCue').onclick=()=>$('#shop').scrollIntoView({behavior:'smooth'});
$$('[data-jump]').forEach(b=>b.onclick=()=>{if(!localStorage.getItem('ff_sell_name')){$('#nameStep').scrollIntoView({behavior:'smooth',block:'center'});toastMsg('Save your name first.')}else renderCategory(b.dataset.jump)});
function renderCategory(cat){currentCategory=cat;currentPayment=null;currentLevel=null;currentRate=null;currentDiscount=0;couponUsed=false;productStep.classList.remove('locked');productTitle.textContent=products[cat].title;productHint.textContent=products[cat].hint;$$('.category-card').forEach(b=>b.classList.toggle('selected',b.dataset.category===cat));if(cat==='topup'){productGrid.className='product-grid';productGrid.innerHTML=products[cat].items.map((x,i)=>`<button class="topup-product" data-topup="${i}"><h4>${x.name}</h4><p>${x.note}</p><div class="go"><span>Full Payment</span><b>Choose →</b></div></button>`).join('');$$('[data-topup]').forEach(b=>b.onclick=()=>openTopup(Number(b.dataset.topup)));}else{productGrid.className='product-grid';productGrid.innerHTML=`<div class="payment-stack"><button class="flow-card" data-payment="Full Payment"><div class="icon">₹</div><h4>Full Payment</h4><p>Pay the full selected rate.</p><div class="go"><span>100%</span><b>Continue →</b></div></button><button class="flow-card" data-payment="Half Payment"><div class="icon">½</div><h4>Half Payment</h4><p>Pay 50% after selecting the ID level and rate.</p><div class="go"><span>50%</span><b>Continue →</b></div></button></div>`;$$('[data-payment]').forEach(b=>b.onclick=()=>{currentPayment=b.dataset.payment;openLevels()})}selectionText.textContent=`${products[cat].title} selected`;selectionMeta.textContent=cat==='topup'?'Choose a top-up item.':'Choose Full Payment or Half Payment.';productStep.scrollIntoView({behavior:'smooth',block:'center'})}
$$('.category-card').forEach(b=>b.onclick=()=>{if(localStorage.getItem('ff_sell_name'))renderCategory(b.dataset.category);else toastMsg('Save your name first.')});
function openLevels(){modalCategory.textContent=currentCategory==='ff'?'FF ID':'BGMI ID';modalTitle.textContent=currentPayment;modalDesc.textContent='Select your level, then choose one of the available rates.';modalBody.innerHTML=`<button class="back-link" id="backToPay">← Back to payment</button><div class="level-list">${products[currentCategory].levels.map((l,i)=>`<div class="level-card"><div class="level-head"><strong>${l.name}</strong><span class="rate-pill">${currentPayment}</span></div><p>${l.note}</p><div class="rate-grid">${rates.map(r=>`<button class="rate-btn" data-rate="${r}" data-level="${i}"><b>${fmt(r)}</b><span>${currentPayment==='Half Payment'?fmt(r/2)+' now':'Full amount'}</span></button>`).join('')}</div></div>`).join('')}</div>`;openModal();$('#backToPay').onclick=()=>{closeModal();renderCategory(currentCategory)};$$('[data-rate]').forEach(b=>b.onclick=()=>openSummary(Number(b.dataset.rate),Number(b.dataset.level)))}
function openTopup(i){currentPayment='Full Payment';currentLevel=products.topup.items[i].name;currentRate=i===0?2999:4999;currentDiscount=0;couponUsed=true;modalCategory.textContent='LOW COST TOP UP';modalTitle.textContent=currentLevel;modalDesc.textContent='Review the full-payment order before confirming.';modalBody.innerHTML=summaryHtml(true);openModal()}
function openSummary(rate,levelIndex){currentLevel=products[currentCategory].levels[levelIndex].name;currentRate=rate;currentDiscount=0;couponUsed=false;modalCategory.textContent=currentCategory==='ff'?'FF ID':'BGMI ID';modalTitle.textContent='Review your order';modalDesc.textContent='Check the details, apply FF200 if eligible, then confirm.';modalBody.innerHTML=summaryHtml(false);openModal()}
function summaryHtml(isTopup){let base=currentPayment==='Half Payment'?currentRate/2:currentRate;return `<div class="summary-box"><div class="summary-row"><span>Category</span><strong>${escapeHtml(products[currentCategory].title)}</strong></div><div class="summary-row"><span>Level / Product</span><strong>${escapeHtml(currentLevel)}</strong></div><div class="summary-row"><span>Payment</span><strong>${escapeHtml(currentPayment)}</strong></div>${!isTopup?`<div class="summary-row"><span>Rate</span><strong>${fmt(currentRate)}</strong></div>`:''}${!isTopup&&currentCategory==='ff'?`<div class="coupon-row"><input id="couponInput" placeholder="Coupon code" maxlength="12" autocomplete="off"><button id="checkCoupon" type="button">Check Coupon</button></div><div class="coupon-msg" id="couponMsg">FF200 gives Rs 200 off once on FF IDs.</div>`:''}<div class="summary-row"><span>Discount</span><strong id="discountLine">− ${fmt(0)}</strong></div><div class="summary-row total"><span>Total</span><strong id="finalAmount">${fmt(base)}</strong></div><button class="action-btn" id="confirmOrder">Confirm Order →</button></div>`}
function applyCoupon(){const input=$('#couponInput'),msg=$('#couponMsg');if(!input||!msg)return;if(currentCategory!=='ff'){msg.textContent='Coupon not available for this category.';return}if(couponUsed){msg.textContent='FF200 has already been used for this order.';return}if(input.value.trim().toUpperCase()==='FF200'){currentDiscount=200;couponUsed=true;const base=currentPayment==='Half Payment'?currentRate/2:currentRate;$('#discountLine').textContent=`− ${fmt(currentDiscount)}`;$('#finalAmount').textContent=fmt(Math.max(0,base-currentDiscount));msg.textContent='✓ FF200 applied: Rs 200 OFF (one time).';input.disabled=true;$('#checkCoupon').disabled=true;toastMsg('FF200 applied.')}else msg.textContent='Invalid coupon code.'}
function submitOrder(){const base=currentPayment==='Half Payment'?currentRate/2:currentRate;const amount=Math.max(0,base-currentDiscount);const order={customer:localStorage.getItem('ff_sell_name')||'Guest',category:products[currentCategory].title,product:currentLevel,level:currentLevel,payment:currentPayment,rate:currentRate,amount,coupon:currentDiscount?'FF200':''};const btn=$('#confirmOrder');btn.disabled=true;btn.textContent='Processing...';STORE_API.createOrder(order).then(created=>{const id=created?.id||'';modalBody.innerHTML=`<div class="processed-card"><div class="processed-icon">✓</div><h3>Order Processed</h3><p>Contact to your dealer for payment details and payout.</p>${id?`<div class="processed-note">Order ID: <strong>${escapeHtml(id)}</strong></div>`:''}<div class="processed-note">Your order has been recorded in the shared order system.</div></div>`;selectionText.textContent='Order processed';selectionMeta.textContent=`${currentLevel} • ${fmt(amount)}`;toastMsg('Order processed successfully.')}).catch(e=>{btn.disabled=false;btn.textContent='Confirm Order →';toastMsg(e.message)})}
function openModal(){modal.classList.remove('hidden');document.body.style.overflow='hidden'}function closeModal(){modal.classList.add('hidden');document.body.style.overflow=''}
$('#modalClose').onclick=closeModal;$$('[data-close]').forEach(x=>x.onclick=closeModal);modal.addEventListener('click',e=>{if(e.target.id==='checkCoupon')applyCoupon();if(e.target.id==='confirmOrder')submitOrder()});
const ordersModal=$('#ordersModal'),ordersBody=$('#ordersModalBody');
function showOrdersLogin(){ordersBody.innerHTML=`<div class="orders-password"><input id="ordersPassword" type="password" placeholder="Dealer password" autocomplete="current-password"><button class="action-btn" id="ordersLogin" style="width:auto;margin:0;padding-inline:18px">Enter</button></div>`;$('#ordersLogin').onclick=loadOrders;$('#ordersPassword').addEventListener('keydown',e=>{if(e.key==='Enter')loadOrders()});openOrders()}
function openOrders(){ordersModal.classList.remove('hidden');document.body.style.overflow='hidden';setTimeout(()=>$('#ordersPassword')?.focus(),60)}function closeOrders(){ordersModal.classList.add('hidden');document.body.style.overflow=''}$('#checkOrdersTop').onclick=showOrdersLogin;$('#ordersClose').onclick=closeOrders;$$('[data-close-orders]').forEach(x=>x.onclick=closeOrders);
function loadOrders(){const p=$('#ordersPassword').value;if(!p)return toastMsg('Enter the dealer password.');const login=$('#ordersLogin');if(login){login.disabled=true;login.textContent='Loading...'}STORE_API.listOrders(p).then(list=>{ordersBody.innerHTML=`<div class="orders-list">${list.length?list.map(order=>`<article class="order-card"><div class="order-card-head"><strong>${escapeHtml(order.id)}</strong><span class="order-status ${order.completed?'completed':''}">${order.completed?'COMPLETED':'PENDING'}</span></div><div class="order-grid"><div><span>Customer</span><b>${escapeHtml(order.customer)}</b></div><div><span>Item</span><b>${escapeHtml(order.level||order.product)}</b></div><div><span>Payment</span><b>${escapeHtml(order.payment)}</b></div><div><span>Amount</span><b>${fmt(order.amount||0)}</b></div></div><div class="order-card-footer"><small>${new Date(order.time).toLocaleString()}</small><button class="complete-order-btn" data-complete="${escapeHtml(order.id)}" data-state="${order.completed?'1':'0'}">${order.completed?'Mark Pending':'Mark Completed'}</button></div></article>`).join(''):'<div class="empty-orders">No orders saved yet.</div>'}</div>`;$$('[data-complete]').forEach(b=>b.onclick=async()=>{try{b.disabled=true;await STORE_API.setOrderCompleted(b.dataset.complete,p,!Number(b.dataset.state));await loadOrders()}catch(e){b.disabled=false;toastMsg(e.message)}})}).catch(e=>{toastMsg(e.message);if(login){login.disabled=false;login.textContent='Enter'}})}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
$('#menuToggle').onclick=()=>{const nav=$('#mainNav');const open=nav.classList.toggle('open');$('#menuToggle').setAttribute('aria-expanded',String(open))};
$$('#mainNav a').forEach(a=>a.addEventListener('click',()=>{$('#mainNav').classList.remove('open');$('#menuToggle').setAttribute('aria-expanded','false')}));
$('#copyCoupon').onclick=async()=>{try{await navigator.clipboard.writeText('FF200');toastMsg('FF200 copied to clipboard.')}catch{toastMsg('Coupon: FF200')}};
$('#supportBtn').onclick=()=>toastMsg('Support link is ready to be connected.');
const backTop=$('#backTop');window.addEventListener('scroll',()=>{backTop.classList.toggle('show',scrollY>500);const links=$$('#mainNav a');const sections=links.map(a=>document.querySelector(a.getAttribute('href'))).filter(Boolean);let current='home';sections.forEach(s=>{if(scrollY+130>=s.offsetTop)current=s.id});links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${current}`))},{passive:true});backTop.onclick=()=>scrollTo({top:0,behavior:'smooth'});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!modal.classList.contains('hidden'))closeModal();if(!ordersModal.classList.contains('hidden'))closeOrders();}});
